# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
      set -e
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none
      export PATH=$PATH:$HOME/.cargo/bin
      rustup toolchain install $RUSTUP_TOOLCHAIN
      rustup default $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  env:
    RUSTUP_TOOLCHAIN: ${{parameters.rust_version}}
  displayName: 'Install rust'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
