[package]
name = "simple_raytracer"
version = "0.1.0"
edition = "2018"
authors = ["Matthieu <matthieu.zandecki@gmail.com>"]

[dependencies]
image = "0.19.0"
cgmath = "*"
rand = "^0.6"
rayon = "*"
indicatif = "0.9.0"